import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs/index.js";

import {
  AiFillLinkedin,
  AiFillYoutube,
  AiFillMail,
} from "react-icons/ai/index.js";
import Image from "next/image";
import avatar from "../public/avatar.webp";

import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import gerichSS from "../public/gerichSS.png";
import gpt from "../public/gpt.png";
import genZ from "../public/genZ.png";
import hcs from "../public/hcs.png";
import pic from "../public/pic.jpg";
import todo from "../public/to-do.png";
import piano from "../public/piano.png";
import ecommerce from "../public/ecommerce.png";
import nexa from "../public/nexa.png";
import white from "../public/white.png";
import { useState } from "react";
// import Services from "../components/Services";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Haneenaz Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">genzee</h1>
            <ul className="flex">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://docs.google.com/document/d/1jQtMaWQr56G0ARTSc5W7gN3QrMfSM5afosP_gywYctY/edit?usp=sharing"
                  target="_blank"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-300">
              Haneena Zainab
            </h2>
            <h3 className="text-2xl text-black py-2 md:text-3xl dark:text-white">
              Your next Front-End Developer
            </h3>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white text-white md:text-3xl max-w-lg mx-auto ">
              Developing and Designing Websites, Web Applications using but not
              limited to JavaScript, React and Webflow.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a
              href="mailto:zhaneena@gmail.com"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillMail />
            </a>
            <a
              href="https://www.linkedin.com/in/haneena-zainab-871a53220/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://www.youtube.com/channel/UCNbwdrniI_7VN-ZqHp48YcA"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillYoutube />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={avatar} layout="fill" objectFit="cover" alt="" />
          </div>
          {/* */}
          {/* <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden bg-clip-text inline-block md:h-96 md:w-96 border-radius-50%">
            <Image
              src={pic}
              layout="fill"
              objectFit="cover"
              objectPosition="center 5%"
            />
          </div> */}
        </section>
        {/*  */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white font-semibold">
              Services I offer
            </h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-white">
              I am a web developer and designer. I can design websites and web
              applications using tools like figma. I can develop web apps using
              Visual Website Builder like{" "}
              <span className="text-teal-500 pr-2 pl-2 dark:text-teal-300">
                Webflow
              </span>
              and wordpress.
            </p>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-white">
              I can also develop web applications using
              <span className="text-teal-500 pr-2 pl-2 dark:text-teal-300">
                JavaScript
              </span>{" "}
              and
              <span className="text-teal-500 pr-2 pl-2 dark:text-teal-300">
                React
              </span>
              library.
            </p>{" "}
          </div>
          <div className="lg:flex gap-10">
            {/*  */}
            <div className="basis-1/3 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-[#243c5a] ">
              <Image src={design} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Modern Designs: Figma
              </h3>
              <p className="py-2 dark:text-white">
                I did my first job in IT field as a UI/UX Designer. I learned to
                design websites and mobile apps.
              </p>
              <h4 className="py-4 text-teal-500 dark:text-teal-300">
                Design Tools I use
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
            </div>
            {/*  */}
            <div className="basis-1/3 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-[#243c5a] ">
              <Image src={consulting} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Visual Website Builder: Webflow
              </h3>
              <p className="py-2 dark:text-white">
                After Completing my Bachelors Degree in 2023, i did my second
                job in FrontEnd Development. I built two websites using webflow
                which are live now.
              </p>
              <h4 className="py-4 text-teal-500 dark:text-teal-300">
                Development Tools I use
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">Webflow</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              {/* <p className="text-gray-800 py-1 dark:text-white">Illustrator</p> */}
            </div>

            {/*  */}
            <div className="basis-1/3 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-[#243c5a] ">
              <Image src={code} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Front-End Development
              </h3>
              <p className="py-2 dark:text-white">
                I was first introduced to coding in my college. I have built
                several web apps as projects in my college and as self practice
                projects.
              </p>
              <h4 className="py-4 text-teal-500 dark:text-teal-300">
                Programming Languages, Library, CSS Frameworks
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">JavaScript</p>
              <p className="text-gray-800 py-1 dark:text-white">React</p>
              <p className="text-gray-800 py-1 dark:text-white">
                Bootstrap and Tailwind CSS
              </p>
            </div>
          </div>
        </section>

        {/*  */}

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white font-semibold">
              Portfolio
            </h3>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-white">
              Below are some of the projects i have done.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={gpt}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-white/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-200 py-5 bg-clip-text">
                  GPT Site
                </h1>
                <div>
                  <a
                    href="https://github.com/haneenapro/gpt_3.git"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>View Code</button>
                  </a>
                  <a
                    href="https://haneena-gpt3.netlify.app/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>Live Site</button>
                  </a>
                </div>
              </div>
            </div>
            {/*  */}
            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={gerichSS}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-white/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-500 py-5 bg-clip-text">
                  My Restaurant
                </h1>
                <div>
                  <a
                    href="https://github.com/haneenapro/My-Restaurant.git"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>View Code</button>
                  </a>
                  <a
                    href="https://haneena-restaurant.netlify.app/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>Live Site</button>
                  </a>
                </div>
              </div>
            </div>

            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={ecommerce}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-black/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-200 py-5 bg-clip-text">
                  E-commerce Site
                </h1>
                <div>
                  <a
                    href="https://github.com/haneenapro/E-commerce-Site.git"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>View Code</button>
                  </a>
                  <a
                    href="https://haneena-ecommerce-site.netlify.app/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>Live Site</button>
                  </a>
                </div>
              </div>
            </div>

            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={hcs}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-black/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-200 py-5 bg-clip-text">
                  Health Consultation System
                </h1>
                <div>
                  <a
                    href="https://github.com/haneenapro/health-app.git"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>View Code</button>
                  </a>
                  <a
                    href="https://health-consulation-system.netlify.app/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>Live Site</button>
                  </a>
                </div>
              </div>
            </div>
            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={genZ}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-black/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-300 py-5 bg-clip-text">
                  Mobile App Share Market
                </h1>
                <div>
                  <a
                    href="https://www.figma.com/file/QnxXT682ZBwbTakOX6KWHY/Untitled?type=design&mode=design&t=vq7LKz3nbZUnZCS9-1"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>View Design</button>
                  </a>
                </div>
              </div>
            </div>
            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={piano}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-black/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-300 py-5 bg-clip-text">
                  Piano
                </h1>
                <div>
                  <a
                    href="https://github.com/haneenapro/Piano-jS.git"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>View Code</button>
                  </a>
                  <a
                    href="https://haneena-piano-javascript.netlify.app/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>Live Site</button>
                  </a>
                </div>
              </div>
            </div>
            {/* <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={todo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <div className="absolute h-full w-full bg-black/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-300 py-5 bg-clip-text">
                  To Do List
                </h1>
                <div>
                  <a
                    href="https://github.com/haneenapro/To-Do-List.git"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                  >
                    <button>View Code</button>
                  </a>
                  <a
                    href="https://haneena-todo.netlify.app/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                  >
                    <button>Live Site</button>
                  </a>
                </div>
              </div>
            </div> */}
          </div>

          <div>
            <p className="text-lg py-2 leading-8 text-gray-800 dark:text-white">
              Published Sites: Made using Webflow
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={nexa}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              <div className="absolute h-full w-full bg-white/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-200 py-5 bg-clip-text">
                  Nexa Equity
                </h1>
                <div>
                  <a
                    href="https://www.nexaequity.com/"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <button>Website</button>
                  </a>
                </div>
              </div>
            </div>
            {/*  */}
            <div className="group basis-1/3 flex-1 relative overflow-hidden">
              <Image
                src={white}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt=""
              />
              {/* <div className="absolute h-full w-full bg-white/30 flex flex-col items-center justify-center -bottom-10 group-hover:bottom-0 opacity-0 group-hover:opacity-100 transition-all duration-300">
                <h1 className="font-semibold text-xl text-teal-500 py-5 bg-clip-text">
                  Taurus
                </h1>
                <div>
                  <a
                    href="#"
                    class="bg-black text-white py-2 px-5 ml-2"
                    target="_blank"
                  >
                    <button> Website</button>
                  </a>
                </div>
              </div> */}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

//Later : change Profile section and services section with crytical coder white, Navbar
//Texts: starting from services: improve
//Now: Porfolio, experience
